// Code generated by "fielder -type=UserAccount -suffix=Column -embedded=true -tag=db -excluded=FullName"; DO NOT EDIT.

package example

type UserAccountColumn string

const (
	UserAccountColumnID        = "id"
	UserAccountColumnCreatedAt = "created_at"
	UserAccountColumnUpdatedAt = "updated_at"
	UserAccountColumnFirstName = "name"
	UserAccountColumnLastName  = "surname"
	UserAccountColumnEmail     = "email"
	UserAccountColumnPassword  = "password"
)

var _UserAccountColumnValues = [...]UserAccountColumn{
	UserAccountColumnID,
	UserAccountColumnCreatedAt,
	UserAccountColumnUpdatedAt,
	UserAccountColumnFirstName,
	UserAccountColumnLastName,
	UserAccountColumnEmail,
	UserAccountColumnPassword,
}

func (x UserAccountColumn) IsValid() bool {
	for _, v := range _UserAccountColumnValues {
		if v == x {
			return true
		}
	}

	return false
}

func (x UserAccountColumn) String() string {
	return string(x)
}

func UserAccountColumnValues() []UserAccountColumn {
	return _UserAccountColumnValues[:]
}
