// Code generated by "{{ .CMD }}"; DO NOT EDIT.

package {{ .Package }}

type {{ .Type }}{{ .Suffix }} string

const (
   {{ range .Fields -}}
      {{ $.Type }}{{ $.Suffix }}{{ .Name }} = "{{ .Alias }}"
   {{ end }}
)

var _{{ .Type }}{{ .Suffix }}Values = [...]{{ .Type }}{{ .Suffix }}{
   {{ range .Fields -}}
      {{ $.Type }}{{ $.Suffix }}{{ .Name }},
   {{ end }}
}

func (x {{ .Type }}{{ .Suffix }}) IsValid() bool {
   for _, v := range _{{ .Type }}{{ .Suffix }}Values {
      if v == x {
         return true
      }
   }

   return false
}

func (x {{ .Type }}{{ .Suffix }}) String() string {
   return string(x)
}

func {{ .Type }}{{ .Suffix }}Values() []{{ .Type }}{{ .Suffix }} {
   return _{{ .Type }}{{ .Suffix }}Values[:]
}
